spring:
  flyway:
    locations: classpath:db/migration
    sql-migration-prefix: v
    schemas: greeting
  datasource:
    url: jdbc:h2:mem:prod-db;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
  jpa:
    hibernate:
      ddl-auto: none